### ISSUE TITLE
Ordered maps

### ISSUE THREAD

**Issue by luispabon** [elliotchance/phpserialize#11]
I'm trying your lib out to talk to a legacy system that signs payloads in a manner that generates an array which is serialised then hashed to generate a signature. The order in which the serialise method works on the array is therefore important.

Now, if I pass on an ordered map to `phpserialize.Marshal`, I get a string out that's ordered alphabetically by key, which is a problem as hashing this string will produce a different outcome.

Is there any way to respect the order of the incoming ordered map?

**Comment by elliotchance** [comment]
Yes, PHP maintains the order of keys in an object. Go purposely randomises keys in a map when iterating, but will sort them by key when encoding JSON. So, the short answer is no, you cannot maintain the order of a map in Go.

You should not rely on the behaviour of a language, only the specification of the structure. So the correct way is to make sure your data is deterministic before generating the hash. If possible the fix would be to change your initial algorithm to use `ksort` before `json_encode`.

Recently I build a HMAC signer and verifier which has the same requirement. The HTTP headers have to be in deterministic, regardless of order or case sensitivity. Here is the part that the prepares the headers for the larger message to be hashed:

```go
func (signer *HMACSignRequest) Headers() (h []string) {
	for name, values := range signer.request.Header {
		for _, value := range values {
			key := strings.ToLower(name)
			v := strings.TrimSpace(value)
			h = append(h, fmt.Sprintf("%s: %s", key, v))
		}
	}

	sort.Strings(h)

	return
}
```

Unfortunately there it nothing I can do about this issue, so I will close it.

**Comment by luispabon** [comment]
Ah, if it were as simple as tweaking the original app to sort the data, but that would invalidate thousands of signed payloads used in the wild by customers. One cannot simply fix the sins of the past and break BC without consequences. At the end I had to resort to building the serialised string by hand.
