### ISSUE TITLE
a bug for consumeAssociativeArray

### ISSUE THREAD

**Issue by tomjamescn** [elliotchance/phpserialize#17]
in consumeAssociativeArray, return is:
`return result, offset, nil`

but in some nested case, need to cosume final '}' like consumeIndexedArray do:
`return result, offset + 1, nil`

this can solve many nested problems.

i will add a pr for this later.

**Comment by tomjamescn** [comment]
i have add a pr for this issue pr #18

**Comment by elliotchance** [comment]
Thanks @tomjamescn - v1.1.7 is released with your patch. 😄
