### ISSUE TITLE
Deserialise object into map

### ISSUE THREAD

**Issue by jdub** [elliotchance/phpserialize#2]
This package supports deserialising an object into a defined struct, but it would be super handy if it could deserialise into a map, just like an associative array.

`consumeObject` [currently checks](https://github.com/elliotchance/phpserialize/blob/master/consume.go#L147) that the destination interface has correctly named keys.

**Comment by elliotchance** [comment]
I believe this was fixed in a previous version. There is an example of this in `TestUnmarshalObjectIntoMapContainingArray`
