### ISSUE TITLE
Need open for more options

### ISSUE THREAD

**Issue by nicolasopt** [elliotchance/phpserialize#21]
Thank for your helpful script!

Can we modify your mod to make it can decode/encode this object :

`ASGIdentity Object
(
[uuid:protected] => 1
[login:protected] => login_name
[publicKey:protected] => abc
)`

**Comment by elliotchance** [comment]
That output is from `print_r`, not `serialize`. `print_r` returns a human-readable representation and is not meant to be parsed (read by a computer). If you are able to control the output you should use `serialize` (or some other format) instead.

If you're really desperate here is a hack someone wrote a few years ago (I wouldn't recommend it though): https://stackoverflow.com/questions/14218698/is-there-a-way-to-parse-the-output-of-print-r - of course this is in PHP, so you would need to rewrite it in Go.
